### PR TITLE
Implement gameover screen

### PR DESCRIPTION
**Pull request by HZ991**
implemented gameover screens for snake and breakout

### CODE REVIEW

**Review by bjur781 — CHANGES_REQUESTED** [review]
On breakout and asteroids it still shows the old version of the game over screen. Could these be removed as they're now unnecessary ?

**Comment by HZ991** [comment]
> On breakout and asteroids it still shows the old version of the game over screen. Could these be removed as they're now unnecessary ?

**Comment by HZ991** [comment]
Functionality:
For all games currently implemented, losing all lives/losing will transport the user to the game over the screen. 'menu' button on the game over screen transports the user to the main menu. The play again button should restart each game

**Review by cnat307 — APPROVED** [review]
LGTM. All games have consistent and working game-over screens.

**Pull request merged**
